#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
STAGED_NOTEBOOKS=$(git diff --cached --name-only | grep "^notebooks/.*\.ipynb$")
if ! command -v nbstripout >/dev/null 2>&1; then
  echo "nbstripout is not available in the current environment."
  echo "source ush/load_bokeh.sh to make nbstripout available"
  exit 1
fi
for notebook in ${STAGED_NOTEBOOKS[@]}; do
  nbstripout ${notebook}
  git add ${notebook}
done
