#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
STAGED_NOTEBOOKS=$(git diff --cached --name-only | grep "^notebooks/.*\.ipynb$")
if [[ "$CONDA_DEFAULT_ENV" != "pyDAmonitor"  ]]; then
  echo "source ush/load_pyDAmonitor.sh first"
  exit 1
fi
for notebook in ${STAGED_NOTEBOOKS[@]}; do
  ush/clean_notebooks.py ${notebook}
  git add ${notebook}
done
